version: '3'

services:
    video-streaming:
        build:
            context: ./.docker-compose/video-streaming
            dockerfile: Dockerfile
        image: video-streaming
        volumes:
            - ./video-streaming:/opt/workdir/video-streaming
            - ./tmp/downloaded_videos/:/tmp/downloaded_videos/
            - ./tmp/transcoded_videos/:/tmp/transcoded_videos/
        depends_on:
            - redis
            - rabbitmq
        networks:
            - redis-network
            - rabbitmq-network
    rabbitmq:
        image: 'rabbitmq:3.8.14-management'
        env_file:
            - ./.docker-compose/rabbitmq/.env
        volumes:
            - rabbitmq-volume:/var/lib/rabbitmq/
        networks:
            - rabbitmq-network
    redis:
        image: 'redis:5-alpine'
        environment:
            # the path of password in container
            REDIS_PASS_FILE: /run/secrets/redis-password
        command: [
            "sh", "-c",
            '
            docker-entrypoint.sh
            --requirepass "$$(cat $$REDIS_PASS_FILE)"
            '
            ]

        volumes:
            - redis-volume:/data
            # pass host password to container
            - ./.docker-compose/redis/.redis_pass_file:/run/secrets/redis-password
        networks:
            - redis-network

networks:
    redis-network:
        driver: bridge
    rabbitmq-network:
        driver: bridge

volumes:
    redis-volume:
    rabbitmq-volume:
