version: '3'

services:
    video-streaming:
        build:
            context: ./.docker-compose/video-streaming
            dockerfile: Dockerfile
        image: video-streaming
        volumes:
            - ./video-streaming:/opt/workdir/video-streaming
