version: '3'

services:
    video-streaming:
        networks:
            - minio-object-storage-network
networks:
    minio-object-storage-network:
        external:
            name: object-storage_minio-object-storage-network
##                  ^             ^
##          name: of project    network created inside that project
